openapi: 3.0.1
info:
  title: Memory AI
  description: API do zarządzania pamięcią użytkownika
  version: "1.0.0"
paths:
  /memory/{topic}:
    get:
      summary: Pobierz pamięć
      parameters:
        - in: path
          name: topic
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
    post:
      summary: Zaktualizuj pamięć
      parameters:
        - in: path
          name: topic
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newText:
                  type: string
      responses:
        "200":
          description: Pamięć zaktualizowana
